server:
  port: 8080
spring:
  application:
    name: "TallerNequi"
  devtools:
    add-properties: false
  sql:
    init:
      mode: "always"
  profiles:
    include: null
  redis:
    host: "localhost"
    port: 6379

adapters:
  r2dbc:
    host: "127.0.0.1"
    port: 5432
    database: "postgres"
    schema: "public"
    username: "postgres"
    password: "1234"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
